### PR TITLE
Resolve #9 - Different Handling for Negative "-" and Positive "+" Signs

### LINKED ISSUE #9: Different Handling for Negative "-" and Positive "+" Signs
Hello 

Thanks for the great done job with this library, it is really the only stable and solid solution I could find for Javascript and the code is a state of art, easy to follow and well tested.

I would like to propose a different handling for negative and positive signs 

## The Current behavior 
| Sign  | Behavior           | 
| ------------- |:-------------|
| -      | The minus sign reverse the number sign  
| +      |  always ignored and omitted from the result 

## The New Behavior 
| Sign  | Behavior           | 
| ------------- |:-------------|
| -      | The minus sign creates a "-" in the result if the number is negative; otherwise ignored
| +      |  The plus sign becomes a "+" in the result if the number is positive, or a "-" if the number is negative.

Examples compares between the new and the old behavior : 

| Number | Mask           | Old Behavior| New Behavior
| ------------- |:------------- |:------------- |:-------------|
| -5000.123456789 | -#,##0.######| 5,000.123457 | -5,000.123457|
| 5000.123456789 | -#,##0.######| -5,000.123457 |  5,000.123457|
| -5000.123456789 | #,##0.######| -5,000.123457 |  5,000.123457|
| +5000.123456789 | +#,##0.######| 5,000.123457 |  +5,000.123457|
| +5000.123456789 | #,##0.######| 5,000.123457 |  +5,000.123457|
| -5000.123456789 | +#,##0.######| -5,000.123457 |  -5,000.123457|

The new behavior makes more sense than the old one and it is less confusing. Of course such a change will not be a BC  but I believe It’s worth it

I will send a PR for this feature and I hope it will be merged

### PR DESCRIPTION
**Pull request by hyyan**

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @hyyan!

I agree with what you're saying. The behavior you describe does make more sense. 

This library could use a rewrite, but I'll go ahead and merge this change if you would please fix the failing test.

**Comment by hyyan** [comment]
@Mottie that's great, the tests are passing , but Travis is falling for a different reason, you might want to check that first, but you can try the PR locally and run the tests

**Comment by Mottie** [comment]
Yeah, I see the tests are passing locally... I think it'll be better if I switch the tests to ava.

**Comment by Mottie** [comment]
Cool, I'll go ahead and merge this... I won't update npm until I get stuff cleaned up.

**Comment by Mottie** [comment]
I've published, then unpublished the changes made by this PR... I think it would be better to add this behavior behind an option. I just can't figure out what to name it.

I think it's weird to completely ignore the negative value here:

```js
format('#,##0.######', -5000.123456789); //=> 5,000.123457
```

So I was going to name the option `forceMaskSign`, but then if the value isn't negative, it's not really forcing a positive sign:

```js
format('-#,##0.######', 5000.123456789); //=> 5,000.123457
```

Was this intended? What do you think the option should be named? Maybe `enforceMaskSign`?

**Comment by rotsee** [comment]
I would like to see this PR somehow re-implemented. 
I was trying to use this lib to parse [subpatterns](http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns) drawn from CLDR, but stumbled on explicit plus signs not working as expected!

**Comment by Mottie** [comment]
I cleaned up the code, added an `enforceMaskSign` option and published v2.0.5 to npm.

The "complete" rewrite to implement the other open enhancement requests hasn't been finished yet.

**Pull request merged**
